# Generated by Django 3.0.6 on 2020-05-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accounting', models.ManyToManyField(to='eshop.Accounting')),
            ],
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.App')),
            ],
        ),
        migrations.RemoveField(
            model_name='leaditem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='leaditem',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='LeadItem',
        ),
        migrations.AddField(
            model_name='accounting',
            name='app',
            field=models.ManyToManyField(to='eshop.App'),
        ),
        migrations.AddField(
            model_name='lead',
            name='app',
            field=models.ManyToManyField(to='eshop.App'),
        ),
    ]
