# Generated by Django 3.0.6 on 2020-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20200515_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(null=True, upload_to='apps'),
        ),
    ]
