# Generated by Django 3.0.6 on 2020-05-16 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_app_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_weeks_in_cycle', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='accounting',
            name='image',
            field=models.ImageField(null=True, upload_to='accounting'),
        ),
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='app',
            name='monthly_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='image',
            field=models.ImageField(null=True, upload_to='payment'),
        ),
        migrations.AddField(
            model_name='app',
            name='addons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.Addon'),
        ),
        migrations.AddField(
            model_name='app',
            name='billing_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.BillingCycle'),
        ),
    ]
