# Generated by Django 3.0.6 on 2020-05-16 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20200516_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='app',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='app',
            name='monthly_volume',
        ),
        migrations.AddField(
            model_name='lead',
            name='addons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.Addon'),
        ),
        migrations.AddField(
            model_name='lead',
            name='billing_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.BillingCycle'),
        ),
        migrations.AddField(
            model_name='lead',
            name='monthly_volume',
            field=models.IntegerField(default=0),
        ),
    ]
