# Generated by Django 3.0.6 on 2020-05-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_auto_20200516_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('volume', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='app',
        ),
        migrations.AddField(
            model_name='lead',
            name='accounting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.Accounting'),
        ),
        migrations.AddField(
            model_name='lead',
            name='app_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.App'),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.Payment'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='monthly_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.MonthlyVolume'),
        ),
    ]
