# Generated by Django 3.0.6 on 2020-05-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_auto_20200516_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='app',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='accounting',
        ),
        migrations.AddField(
            model_name='accounting',
            name='payments',
            field=models.ManyToManyField(to='eshop.Payment'),
        ),
        migrations.AddField(
            model_name='app',
            name='accounting',
            field=models.ManyToManyField(null=True, to='eshop.Accounting'),
        ),
    ]
