# Generated by Django 3.0.6 on 2020-05-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_auto_20200517_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
        ),
    ]
