# Generated by Django 3.0.6 on 2020-05-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_auto_20200518_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyvolume',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
